### ISSUE TITLE
`docs.rs` 按钮的链接不正确 | 无链接或无法使用的情况下按钮应变成不可点击的状态

### ISSUE THREAD

**Issue by zjp-CN** [hehehai/cratehub#14]
![image](https://user-images.githubusercontent.com/25300418/173535890-1e907cc4-1d6c-4a96-8215-af48fea8449c.png)

地址应该是 `https://docs.rs/名称` 或者 `https://docs.rs/名称/latest/` 之类的

**Comment by hehehai** [comment]
@zjp-CN 嗯，谢谢，这个已经修复，chrome 版本的插件，在审核中😅

**Comment by hehehai** [comment]
@zjp-CN 🥰好的，收到，下个版本安排

**Comment by hehehai** [comment]
@zjp-CN 版本已更新
