### ISSUE TITLE
not support Cargo workspace

### ISSUE THREAD

**Issue by baoyachi** [hehehai/cratehub#20]
<img width="1467" alt="image" src="https://user-images.githubusercontent.com/10433001/174698097-c3f21815-33ea-4756-86b4-1d8a96d914fe.png">
<img width="1452" alt="image" src="https://user-images.githubusercontent.com/10433001/174698117-ead6ee84-b4fd-4870-8407-83e8edf52f98.png">

**Comment by hehehai** [comment]
@baoyachi hi, the [repo project](https://github.com/ntex-rs/ntex) workspace in sider box, like this

<img width="1663" alt="image" src="https://user-images.githubusercontent.com/12692552/174699572-496891ee-c841-44c2-a38e-593fa60fb8e7.png">

dependencies only show current repo top Cargo.toml, if you want check workspace member dependencies, you can click the member link, this will focus you on the member Cargo.toml.

<img width="356" alt="image" src="https://user-images.githubusercontent.com/12692552/174699764-bffcee5c-d229-4a38-9ce3-26d0d2d29231.png">

<img width="1609" alt="image" src="https://user-images.githubusercontent.com/12692552/174699931-86678955-5d02-454e-8a73-fa872fd73c8f.png">

**Comment by baoyachi** [comment]
Does slider box collapse expand see detail ? Sometime not want click the member link.

Bytheway, cratehub it's good brower extention. 👍

**Comment by hehehai** [comment]
> Does slider box collapse expand see detail ? Sometime not want click the member link.
> 
> Bytheway, cratehub it's good brower extention. 👍

@baoyachi thx🥰!

You mean workspace member show more detail? Can you describe what information needs to be displayed?

**Comment by baoyachi** [comment]
![workspace](https://user-images.githubusercontent.com/10433001/174702098-c57dd264-719a-4768-afa3-c80b4ffe0f6f.gif)

like this

**Comment by hehehai** [comment]
> ![workspace](https://user-images.githubusercontent.com/10433001/174702098-c57dd264-719a-4768-afa3-c80b4ffe0f6f.gif) [ ](https://user-images.githubusercontent.com/10433001/174702098-c57dd264-719a-4768-afa3-c80b4ffe0f6f.gif)
> 
> like this

Oh, I see. Thank you for your advice!

I think that the current critehub should only be used as a plug-in to display the basic trust ecological information of a repo. More detailed information, such as the file tree of workspace members, You should use GitHub or [Octotree](https://www.octotree.io/)🤔

In addition, for complex file display, private projects such as GitHub token need to be considered, which is a bit tricky😅
